package models

// BuiltinModels is the embedded model registry, generated from
// https://commandcode.ai/docs/reference/cli/models (2026-08-09).
// It is the fallback when remote sync is unavailable. Runtime sync
// refreshes this list from the same docs page.
var BuiltinModels = []ModelEntry{
    {ID: "Qwen/Qwen3.6-Max-Preview", Vendor: "Alibaba", ShortName: "Qwen3.6-Max-Preview", Name: "Qwen3.6-Max-Preview"},
    {ID: "Qwen/Qwen3.6-Plus", Vendor: "Alibaba", ShortName: "Qwen3.6-Plus", Name: "Qwen3.6-Plus"},
    {ID: "Qwen/Qwen3.7-Flash", Vendor: "Alibaba", ShortName: "Qwen3.7-Flash", Name: "Qwen3.7-Flash"},
    {ID: "Qwen/Qwen3.7-Max", Vendor: "Alibaba", ShortName: "Qwen3.7-Max", Name: "Qwen3.7-Max"},
    {ID: "Qwen/Qwen3.7-Plus", Vendor: "Alibaba", ShortName: "Qwen3.7-Plus", Name: "Qwen3.7-Plus"},
    {ID: "Qwen/Qwen3.8-Max", Vendor: "Alibaba", ShortName: "Qwen3.8-Max", Name: "Qwen3.8-Max"},
    {ID: "claude-fable-5", Vendor: "Anthropic", ShortName: "claude-fable-5", Name: "claude-fable-5"},
    {ID: "claude-haiku-4-5", Vendor: "Anthropic", ShortName: "claude-haiku-4-5", Name: "claude-haiku-4-5"},
    {ID: "claude-opus-4-7", Vendor: "Anthropic", ShortName: "claude-opus-4-7", Name: "claude-opus-4-7"},
    {ID: "claude-opus-4-8", Vendor: "Anthropic", ShortName: "claude-opus-4-8", Name: "claude-opus-4-8"},
    {ID: "claude-opus-5", Vendor: "Anthropic", ShortName: "claude-opus-5", Name: "claude-opus-5"},
    {ID: "claude-sonnet-4-6", Vendor: "Anthropic", ShortName: "claude-sonnet-4-6", Name: "claude-sonnet-4-6"},
    {ID: "claude-sonnet-5", Vendor: "Anthropic", ShortName: "claude-sonnet-5", Name: "claude-sonnet-5"},
    {ID: "deepseek/deepseek-v4-flash", Vendor: "DeepSeek", ShortName: "deepseek-v4-flash", Name: "deepseek-v4-flash"},
    {ID: "deepseek/deepseek-v4-pro", Vendor: "DeepSeek", ShortName: "deepseek-v4-pro", Name: "deepseek-v4-pro"},
    {ID: "google/gemini-3.1-flash-lite", Vendor: "Google", ShortName: "gemini-3.1-flash-lite", Name: "gemini-3.1-flash-lite"},
    {ID: "google/gemini-3.5-flash", Vendor: "Google", ShortName: "gemini-3.5-flash", Name: "gemini-3.5-flash"},
    {ID: "google/gemini-3.5-flash-lite", Vendor: "Google", ShortName: "gemini-3.5-flash-lite", Name: "gemini-3.5-flash-lite"},
    {ID: "google/gemini-3.6-flash", Vendor: "Google", ShortName: "gemini-3.6-flash", Name: "gemini-3.6-flash"},
    {ID: "meta/muse-spark-1.1", Vendor: "Meta", ShortName: "muse-spark-1.1", Name: "muse-spark-1.1"},
    {ID: "meta/muse-spark-1.2", Vendor: "Meta", ShortName: "muse-spark-1.2", Name: "muse-spark-1.2"},
    {ID: "meta/muse-spark-1.2-contributor", Vendor: "Meta", ShortName: "muse-spark-1.2-contributor", Name: "muse-spark-1.2-contributor"},
    {ID: "MiniMaxAI/MiniMax-M2.5", Vendor: "MiniMax", ShortName: "MiniMax-M2.5", Name: "MiniMax-M2.5"},
    {ID: "MiniMaxAI/MiniMax-M2.7", Vendor: "MiniMax", ShortName: "MiniMax-M2.7", Name: "MiniMax-M2.7"},
    {ID: "MiniMaxAI/MiniMax-M3", Vendor: "MiniMax", ShortName: "MiniMax-M3", Name: "MiniMax-M3"},
    {ID: "moonshotai/Kimi-K2.5", Vendor: "Moonshot AI", ShortName: "Kimi-K2.5", Name: "Kimi-K2.5"},
    {ID: "moonshotai/Kimi-K2.6", Vendor: "Moonshot AI", ShortName: "Kimi-K2.6", Name: "Kimi-K2.6"},
    {ID: "moonshotai/Kimi-K2.7-Code", Vendor: "Moonshot AI", ShortName: "Kimi-K2.7-Code", Name: "Kimi-K2.7-Code"},
    {ID: "moonshotai/Kimi-K2.7-Code-Highspeed", Vendor: "Moonshot AI", ShortName: "Kimi-K2.7-Code-Highspeed", Name: "Kimi-K2.7-Code-Highspeed"},
    {ID: "moonshotai/Kimi-K3", Vendor: "Moonshot AI", ShortName: "Kimi-K3", Name: "Kimi-K3"},
    {ID: "nvidia/nemotron-3-ultra-550b-a55b", Vendor: "NVIDIA", ShortName: "nemotron-3-ultra-550b-a55b", Name: "nemotron-3-ultra-550b-a55b"},
    {ID: "gpt-5.3-codex", Vendor: "OpenAI", ShortName: "gpt-5.3-codex", Name: "gpt-5.3-codex"},
    {ID: "gpt-5.4", Vendor: "OpenAI", ShortName: "gpt-5.4", Name: "gpt-5.4"},
    {ID: "gpt-5.4-mini", Vendor: "OpenAI", ShortName: "gpt-5.4-mini", Name: "gpt-5.4-mini"},
    {ID: "gpt-5.5", Vendor: "OpenAI", ShortName: "gpt-5.5", Name: "gpt-5.5"},
    {ID: "gpt-5.6-luna", Vendor: "OpenAI", ShortName: "gpt-5.6-luna", Name: "gpt-5.6-luna"},
    {ID: "gpt-5.6-sol", Vendor: "OpenAI", ShortName: "gpt-5.6-sol", Name: "gpt-5.6-sol"},
    {ID: "gpt-5.6-terra", Vendor: "OpenAI", ShortName: "gpt-5.6-terra", Name: "gpt-5.6-terra"},
    {ID: "poolside/laguna-s-2.1-free", Vendor: "Poolside", ShortName: "laguna-s-2.1-free", Name: "laguna-s-2.1-free"},
    {ID: "sakana/fugu-ultra", Vendor: "Sakana AI", ShortName: "fugu-ultra", Name: "fugu-ultra"},
    {ID: "stepfun/Step-3.5-Flash", Vendor: "StepFun", ShortName: "Step-3.5-Flash", Name: "Step-3.5-Flash"},
    {ID: "stepfun/Step-3.7-Flash", Vendor: "StepFun", ShortName: "Step-3.7-Flash", Name: "Step-3.7-Flash"},
    {ID: "tencent/hy3-paid", Vendor: "Tencent", ShortName: "hy3-paid", Name: "hy3-paid"},
    {ID: "thinkingmachines/inkling", Vendor: "Thinking Machines", ShortName: "inkling", Name: "inkling"},
    {ID: "thinkingmachines/inkling-small", Vendor: "Thinking Machines", ShortName: "inkling-small", Name: "inkling-small"},
    {ID: "xai/grok-4.5", Vendor: "xAI", ShortName: "grok-4.5", Name: "grok-4.5"},
    {ID: "xiaomi/mimo-v2.5", Vendor: "Xiaomi", ShortName: "mimo-v2.5", Name: "mimo-v2.5"},
    {ID: "xiaomi/mimo-v2.5-pro", Vendor: "Xiaomi", ShortName: "mimo-v2.5-pro", Name: "mimo-v2.5-pro"},
    {ID: "zai-org/GLM-5", Vendor: "Z AI", ShortName: "GLM-5", Name: "GLM-5"},
    {ID: "zai-org/GLM-5.1", Vendor: "Z AI", ShortName: "GLM-5.1", Name: "GLM-5.1"},
    {ID: "zai-org/GLM-5.2", Vendor: "Z AI", ShortName: "GLM-5.2", Name: "GLM-5.2"},
    {ID: "zai-org/GLM-5.2-Fast", Vendor: "Z AI", ShortName: "GLM-5.2-Fast", Name: "GLM-5.2-Fast"},
}